name: YunshengZhao Lab3 YAML File

on: push

jobs:
  yunshenglab3build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Lab 3 Java JDK
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4.7.0
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  yunshenglab3test:
    needs: yunshenglab3build
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4.7.0
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      run: mvn test

  yunshenglab3deploy:
    needs: [yunshenglab3build, yunshenglab3test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Simulate deployment
      run: |
        echo "Deploying to production..."
        echo "Deployment successful!"
